(() => {
'use strict';
const D=DN,{state,$,$$,icon,escape}=D;
const types={};
const sample=items=>{if(!D.young()&&!state.settings.reduced)return items;const yes=items.filter(x=>x[1]===true),no=items.filter(x=>x[1]===false);return yes.length?items.filter(x=>yes.slice(0,D.rank()===0?2:3).includes(x)||no.slice(0,D.rank()===0?1:2).includes(x)):items.slice(0,D.rank()===0?3:6);};
const shuffled=arr=>arr.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]);
const instruction=t=>`<div class="instruction">${icon('hand')}<span>${escape(t)}</span></div>`;
const checkButton=(label='Проверить результат')=>`<button class="primary check-button" id="check-task">${label} ${icon('arrow')}</button>`;
let G;
function mount(w,s,i){
 const k=D.key(w.id,i),r=state.runs[k]||(state.runs[k]={errors:0,hinted:false,paid:[],data:{}});
 G={w,s,i,k,r,paused:false,completed:false,cleanup:[],data:r.data,
  store(){D.save();},
  action(token,msg){if(G.completed)return;if(!r.paid.includes(token)){r.paid.push(token);if(r.paid.length<=20&&!state.results[k])state.xp+=2;}D.save();D.app.refreshHeader();if(msg)G.feedback(true,msg);D.effect();},
  feedback(ok,msg){$('#feedback').className=ok?'feedback good':'feedback bad';$('#feedback').innerHTML=`${icon(ok?'check':'compass')}<p>${escape(msg)}</p>`;$('#guide-message').textContent=msg;D.voiceText(msg);},
  error(msg){if(G.completed||G.paused)return;r.errors++;D.save();G.feedback(false,msg);D.effect('error');},
  hint(){if(G.completed)return;r.hinted=true;D.save();D.dialog('Подсказка',`<p>${escape(s.hint||'Какое действие поможет проверить ситуацию, не увеличивая риск?')}</p><p class="small-note">Подсказка помогает рассуждать. Скорость работы не влияет на награду.</p>`);D.voice(`hint.${w.id}.${i}`);},
  done(msg){
   if(G.completed)return;G.completed=true;D.stopVoice();G.cleanup.forEach(fn=>fn());
   const earned=r.errors===0&&!r.hinted?3:r.errors<=2?2:1,previous=state.results[k],xp=previous?Math.max(0,earned-previous.stars)*20:80+(!r.hinted?20:0);
   state.xp+=xp;state.results[k]={stars:Math.max(earned,previous?.stars||0),errors:r.errors,hinted:r.hinted,completedAt:Date.now()};
   const rewards={data:['Не сообщай код','Проверь источник','Настрой приватность'],social:['Настрой приватность','Проверь источник'],links:['Проверь источник'],pressure:['Сделай скриншот','Заблокируй'],conflict:['Сделай скриншот','Заблокируй'],truth:['Проверь источник'],games:['Не сообщай код','Проверь источник','Заблокируй'],money:['Проверь источник','Не сообщай код'],free:['Проверь источник','Не сообщай код'],help:['Сделай скриншот','Проверь источник']};
   const newTools=[];if(i===2||i===4)for(const name of new Set([...(rewards[w.id]||[]),...caseConfiguration(w.id).tools]))if(D.awardTool(name))newTools.push(name);
   const worldDone=D.completed(w.id)===5;if(worldDone)D.awardTool(w.reward);
   state.resume=i<4?{world:w.id,stage:i+1,age:state.age}:null;delete state.runs[k];D.save();D.app.refreshHeader();D.effect(worldDone?'reward':'success');
   $('#feedback').className='completion';$('#feedback').innerHTML=`<div class="completion-stars">${[1,2,3].map(n=>icon('star',n<=earned?'earned':'')).join('')}</div><h2>${worldDone?'Мир завершён!':'Этап пройден!'}</h2><p>${escape(msg)}</p><div class="result-chips"><span>+${xp} XP</span><span>${r.errors} исправленных ошибок</span><span>${r.hinted?'С подсказкой':'Самостоятельно'}</span></div>${newTools.length?`<p class="tool-award">${icon('bag')} В рюкзаке: ${escape(newTools.join(', '))}</p>`:''}${worldDone?`<p class="tool-award">${icon('trophy')} Достижение «${escape(w.achievement)}»</p>`:''}<div class="result-actions"><button class="primary" id="continue-stage">${i<4?'Следующий этап':'К локации'} ${icon('arrow')}</button><button class="secondary" id="repeat-stage">Повторить</button><button class="secondary" id="to-map">На карту</button></div>`;
   $('#continue-stage').onclick=()=>i<4?D.app.play(w.id,i+1):D.app.location(w.id);$('#repeat-stage').onclick=()=>D.app.play(w.id,i);$('#to-map').onclick=D.app.map;
   $('#activity').classList.add('activity-finished');$('#activity').inert=true;$('#feedback').scrollIntoView({block:'nearest',behavior:state.settings.calm?'auto':'smooth'});D.voiceText(msg);
  }
 };
 D.game=G;
 types[s.type]($('#activity'),s);
 return ()=>{G.cleanup.forEach(fn=>fn());G.cleanup=[];};
}
/* Одно перетаскивание для мыши и touch. Альтернатива: карточка → зона. */
function drag(root,accept){
 let selected=null,pending=null,ghost=null,lastDrag=0;
 const select=el=>{root.querySelectorAll('[data-drag]').forEach(c=>c.classList.remove('selected'));selected=el;el?.classList.add('selected');};
 const down=e=>{const card=e.target.closest('[data-drag]');if(!card||G.completed||G.paused||e.button>0)return;pending={card,x:e.clientX,y:e.clientY,id:e.pointerId};};
 const move=e=>{if(!pending||pending.id!==e.pointerId)return;if(!ghost&&Math.hypot(e.clientX-pending.x,e.clientY-pending.y)>8){ghost=pending.card.cloneNode(true);ghost.classList.add('drag-ghost');ghost.style.width=pending.card.getBoundingClientRect().width+'px';document.body.appendChild(ghost);select(pending.card);}if(ghost){e.preventDefault();ghost.style.left=e.clientX+12+'px';ghost.style.top=e.clientY+12+'px';}};
 const up=e=>{if(!pending)return;if(ghost){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-drop]');if(target&&root.contains(target))accept(pending.card.dataset.drag,target.dataset.drop);ghost.remove();ghost=null;lastDrag=Date.now();select(null);}pending=null;};
 const click=e=>{if(Date.now()-lastDrag<250||G.completed||G.paused)return;const card=e.target.closest('[data-drag]'),target=e.target.closest('[data-drop]');if(card){select(selected===card?null:card);}else if(target&&selected){accept(selected.dataset.drag,target.dataset.drop);select(null);}};
 const keyboard=e=>{if(!['Enter',' '].includes(e.key)||G.completed||G.paused)return;const target=e.target.closest('[data-drop]');if(target&&selected&&!e.target.closest('[data-drag]')){e.preventDefault();accept(selected.dataset.drag,target.dataset.drop);select(null);}};
 root.addEventListener('pointerdown',down);root.addEventListener('click',click);root.addEventListener('keydown',keyboard);document.addEventListener('pointermove',move,{passive:false});document.addEventListener('pointerup',up);document.addEventListener('pointercancel',up);
 const remove=()=>{ghost?.remove();root.removeEventListener('pointerdown',down);root.removeEventListener('click',click);root.removeEventListener('keydown',keyboard);document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);document.removeEventListener('pointercancel',up);};G.cleanup.push(remove);return remove;
}
types.sort=(a,s)=>{
 const items=(D.young()||state.settings.reduced)?s.items.slice(0,D.rank()===0?3:6):s.items;const positions=G.data.positions||(G.data.positions={});
 function draw(){a.innerHTML=instruction('Перетащи карточку в зону или нажми сначала на карточку, затем на зону.')+`<div class="sort-bank">${items.map(([t],i)=>positions[i]===undefined?`<button class="drag-card" data-drag="${i}">${escape(t)}</button>`:'').join('')}</div><div class="sort-zones">${s.zones.map((z,n)=>`<section class="drop-zone" data-drop="${n}" tabindex="0" role="button" aria-label="${escape(z)}"><h3>${escape(z)}</h3><div>${items.map(([t],i)=>positions[i]===n?`<button class="drag-card placed" data-drag="${i}">${escape(t)}</button>`:'').join('')}</div></section>`).join('')}</div>${checkButton()}`;}
 draw();drag(a,(id,zone)=>{positions[id]=Number(zone);G.action('place'+id);draw();});
 a.addEventListener('click',e=>{if(e.target.closest('#check-task')){if(items.some((x,i)=>positions[i]===undefined)){G.error('В зонах пока не все карточки. Заверши распределение.');return;}const wrong=items.findIndex((x,i)=>positions[i]!==x[1]);if(wrong<0)G.done(s.zones.length===3?'Ты подобрал поддержку к ситуации. Можно привлечь несколько подходящих людей одновременно.':'Ты различил последствия и распределил сведения или действия по назначению.');else{const t=items[wrong][0];G.error(`Карточка «${t}» пока не на подходящем месте. ${s.hint}`);}}});
};
types.puzzle=(a,s)=>{
 const pairs=D.young()||state.settings.reduced?s.pairs.slice(0,D.rank()===0?3:4):s.pairs;const positions=G.data.positions||(G.data.positions={});const order=G.data.order||(G.data.order=shuffled(pairs.map((_,i)=>i)));
 function draw(){a.innerHTML=instruction('Соедини разделы и настройки. Карточку можно переносить и исправлять.')+`<div class="puzzle-board"><div class="puzzle-slots">${pairs.map(([name],i)=>`<section data-drop="${i}" class="puzzle-slot" role="button" tabindex="0"><b>${escape(name)}</b><span>${Object.entries(positions).filter(([id,p])=>p===i).map(([id])=>`<button class="drag-card" data-drag="${id}">${escape(pairs[id][1])}</button>`).join('')||'Помести деталь сюда'}</span></section>`).join('')}</div><div class="puzzle-pieces">${order.filter(i=>positions[i]===undefined).map(i=>`<button class="drag-card puzzle-piece" data-drag="${i}">${icon('puzzle')}${escape(pairs[i][1])}</button>`).join('')}</div></div><div class="configuration-meter"><span>Собрано ${Object.keys(positions).length} / ${pairs.length}</span><div class="meter"><i style="width:${Object.keys(positions).length/pairs.length*100}%"></i></div></div>${checkButton('Применить сборку')}`;}
 draw();drag(a,(id,slot)=>{const previous=Object.entries(positions).find(([other,p])=>p===Number(slot)&&other!==id);if(previous)delete positions[previous[0]];positions[id]=Number(slot);G.action('puzzle'+id);draw();});a.addEventListener('click',e=>{if(e.target.closest('#check-task')){if(pairs.every((x,i)=>positions[i]===i))G.done('Каждая проверка или настройка соединена со своей задачей. Ты собрал рабочую защиту, а не просто красивую страницу.');else G.error('Проверь связи: какая деталь решает именно эту задачу? Можно переставлять карточки.');}});
};
types.sequence=(a,s)=>{
 const youngIndices={links:[0,1,2],pressure:[0,1,3],conflict:[0,1,3],money:[0,1,3],help:[0,2,4]};
 const steps=D.rank()===0?(youngIndices[G.w.id]||[0,1,2]).map(i=>s.steps[i]):s.steps;
 const decoys=D.rank()===0?[]:D.young()||state.settings.reduced?s.decoys.slice(0,1):s.decoys;
 G.data.effectiveSteps=steps;
 if(G.data.order?.length!==steps.length+decoys.length){G.data.order=null;G.data.list=[];}
 const list=G.data.list||(G.data.list=[]);const order=G.data.order||(G.data.order=shuffled([...steps,...decoys]));
 function draw(){a.innerHTML=instruction('Перетащи действия в пронумерованные места. Для исправления перенеси карточку обратно.')+`<div class="sequence-slots">${steps.map((t,i)=>`<section data-drop="${i}" class="sequence-slot" tabindex="0" role="button"><b>${i+1}</b><span>${list[i]!==undefined?`<button data-drag="${list[i]}" class="drag-card">${escape(order[list[i]])}</button>`:'Твоё действие'}</span></section>`).join('')}</div><div class="sequence-bank" data-drop="bank">${order.map((t,i)=>!list.includes(i)?`<button data-drag="${i}" class="drag-card">${escape(t)}</button>`:'').join('')}</div>${checkButton('Применить план')}`;}
 draw();drag(a,(id,zone)=>{const index=Number(id),prev=list.indexOf(index);if(prev>=0)list[prev]=undefined;if(zone!=='bank'){list[Number(zone)]=index;G.action('order'+id);}else G.store();draw();});a.addEventListener('click',e=>{if(e.target.closest('#check-task')){if(steps.every((t,i)=>order[list[i]]===t))G.done('План позволяет сначала остановиться и проверить ситуацию, затем действовать с учётом риска.');else{const p=steps.findIndex((t,i)=>order[list[i]]!==t);G.error(`Посмотри на шаг ${p+1}: достаточно ли сведений для этого действия? Переставь карточки и попробуй снова.`);}}});
};
types.settings=(a,s)=>{
 const rows=D.young()||state.settings.reduced?s.rows.slice(0,D.rank()===0?3:4):s.rows;
 const settings=G.data.settings||(G.data.settings=rows.map(()=>true));
 a.innerHTML=instruction('Нажимай переключатели. Настройки влияют на работу приложения и доступ к данным.')+`<div class="settings-game"><div class="phone-shell"><div class="phone-top">09:41 <span>● ▮▮▮</span></div><div class="phone-notch"></div><h3>Панель управления</h3>${rows.map(([name],i)=>`<label class="permission-row"><span>${escape(name)}</span><input type="checkbox" data-permission="${i}" ${settings[i]?'checked':''}><i class="switch"></i></label>`).join('')}<div class="phone-home"></div></div><aside class="setting-explain"><div class="setting-orb">${icon('settings')}</div><h3>Твои настройки</h3><p>Параметры можно менять и проверять столько раз, сколько нужно.</p><span id="setting-count"></span>${checkButton('Применить настройки')}</aside></div>`;
 const refresh=()=>$('#setting-count').textContent=`Включено ${settings.filter(Boolean).length} из ${rows.length} функций`;
 $$('[data-permission]').forEach(el=>el.onchange=()=>{settings[Number(el.dataset.permission)]=el.checked;G.action('setting'+el.dataset.permission);refresh();});refresh();$('#check-task').onclick=()=>{const wrong=rows.findIndex((r,i)=>r[1]!==settings[i]);if(wrong<0)G.done('Ты сохранил необходимые функции и отключил лишний доступ или рискованные действия. Настройки теперь работают на твою защиту.');else G.error(`${rows[wrong][0]}: сопоставь эту настройку с назначением функции. Нужные разрешения оставь включёнными, лишние отключи.`);};
};
types.scan=(a,s)=>{
 const items=sample(s.items);const found=G.data.found||(G.data.found=[]);const needed=items.filter(x=>x[1]).length;
 const headings={profile:'Лента · профиль',mail:'Входящие · письмо',chat:'Командный чат',shop:'Оформление заказа',ad:'Карточка рекламного предложения',media:'Исследование публикации'};
 a.innerHTML=instruction('Нажимай прямо на детали внутри окна. Отметь признаки, требующие осторожности.')+`<div class="scene-interface scene-${s.scene}"><div class="window-bar"><i></i><i></i><i></i><span>${headings[s.scene]}</span></div>${s.scene==='profile'?`<div class="profile-banner"><div class="profile-avatar">${icon('people')}</div><div><b>Новая публикация</b><small>Доступна всем пользователям</small></div><div class="profile-art">${icon('camera')}<span>Фото, детали и подпись</span></div></div>`:s.scene==='mail'?'<div class="mail-title"><h3>Уведомление сервиса</h3><span>Сегодня · 09:41</span></div>':s.scene==='media'?`<div class="video-frame">${icon('play')}<span>Короткий ролик · данные публикации</span></div>`:s.scene==='ad'?'<div class="ad-title">БОНУС ДЛЯ ТЕБЯ<small>Исследуй условия предложения</small></div>':''}<div class="scene-details">${items.map(([t,risk],i)=>`<button class="hotspot ${found.includes(i)?'found':''}" data-hotspot="${i}" ${found.includes(i)?'disabled':''}>${escape(t)}${found.includes(i)?icon('check'):''}</button>`).join('')}</div></div><div class="task-counter" id="scan-counter"></div>`;
 const refresh=()=>$('#scan-counter').textContent=`Исследовано значимых деталей: ${found.length} / ${needed}`;refresh();
 $$('[data-hotspot]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.hotspot);if(found.includes(i))return;if(items[i][1]){found.push(i);b.classList.add('found');b.disabled=true;b.insertAdjacentHTML('beforeend',icon('check'));G.action('found'+i,'Эта деталь требует проверки. Посмотри, есть ли другие связанные признаки.');refresh();if(found.length===needed)G.done('Ты нашёл значимые признаки внутри сообщения или профиля. Оформление и знакомое имя не заменяют проверку.');}else G.error('Эта деталь сама по себе не подтверждает опасность. Ищи требования, противоречия и личные сведения в контексте.');});
 if(found.length===needed)G.done('Значимые детали исследованы.');
};
types.chat=(a,s)=>{
 const chat=G.data.chat||(G.data.chat={at:0,history:[],pressure:0});const max=s.nodes.length;
 function draw(){const n=s.nodes[chat.at];a.innerHTML=instruction('Ответь собеседнику. Наблюдай, как твои действия меняют переписку.')+`<div class="messenger"><div class="messenger-top"><span class="npc-avatar">${icon('people')}</span><div><b>${escape(s.npc)}</b><small>Учебная переписка · ${chat.at+1}/${max}</small></div><span class="pressure-meter">Давление: ${chat.pressure}</span></div><div class="chat-history">${chat.history.map(x=>`<div class="bubble ${x.from}">${escape(x.text)}</div>`).join('')}<div class="bubble npc current-message">${escape(n.text)}</div></div><div class="chat-compose"><span>Твой ответ</span>${n.choices.filter((x,i)=>!(state.settings.reduced||D.young())||x.ok||i<2).map((x,i)=>`<button class="chat-reply" data-reply="${n.choices.indexOf(x)}">${escape(x.text)} ${icon('arrow')}</button>`).join('')}</div></div>`;$$('[data-reply]').forEach(b=>b.onclick=()=>{const c=n.choices[Number(b.dataset.reply)];chat.history.push({from:'npc',text:n.text},{from:'self',text:c.text});if(c.ok){chat.pressure=Math.max(0,chat.pressure-1);G.action('chat'+chat.at);chat.at++;if(chat.at>=max){a.querySelector('.chat-compose').innerHTML='';a.querySelector('.chat-history').insertAdjacentHTML('beforeend',`<div class="bubble npc">${escape(c.response)}</div>`);G.done(c.response);return;}G.store();draw();G.feedback(true,c.response);}else{chat.pressure++;chat.history.push({from:'npc',text:c.response});G.error(c.response+' Можно изменить ответ и сохранить свои границы.');draw();} });}
 draw();
};
types.domains=(a,s)=>{
 const addresses=D.young()||state.settings.reduced?s.addresses.slice(0,3):s.addresses;const selected=G.data.selected||(G.data.selected=[]);
 a.innerHTML=instruction('Отметь адреса, которые отличаются от известного домена. Ссылки в лаборатории никуда не ведут.')+`<div class="domain-reference">Известный домен сервиса <b>${escape(s.reference)}</b></div><div class="domain-lab">${addresses.map((t,i)=>`<button data-address="${i}" class="domain-row ${selected.includes(i)?'selected':''}" aria-pressed="${selected.includes(i)}"><span class="address-prefix">https://</span><b>${escape(t)}</b><span>/login</span>${icon('search')}</button>`).join('')}</div>${checkButton('Завершить проверку адресов')}`;
 $$('[data-address]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.address),at=selected.indexOf(i);at>=0?selected.splice(at,1):selected.push(i);b.classList.toggle('selected',selected.includes(i));b.setAttribute('aria-pressed',String(selected.includes(i)));G.action('domain'+i);});$('#check-task').onclick=()=>{if(addresses.every((x,i)=>selected.includes(i)===(i!==s.safe)))G.done('Ты проверил именно домен: похожая буква или знакомое слово в чужом адресе не подтверждают сервис.');else G.error('Сравни весь домен с известным: цифра вместо буквы и добавленное окончание меняют адрес.');};
};
types.evidence=(a,s)=>{
 const items=sample(s.items);const selected=G.data.selected||(G.data.selected=[]);
 a.innerHTML=instruction('Сохрани значимые сведения в пакет обращения. Повторное нажатие убирает объект из пакета.')+`<div class="evidence-workspace"><div class="evidence-source"><div class="window-bar"><span>Доступные сведения</span></div>${items.map(([t],i)=>`<button data-evidence="${i}" class="evidence-item ${selected.includes(i)?'selected':''}">${icon('camera')}<span>${escape(t)}</span><small>${selected.includes(i)?'В пакете':'Сохранить'}</small></button>`).join('')}</div><aside class="evidence-folder">${icon('bag')}<h3>Пакет обращения</h3><div id="evidence-list"></div>${checkButton('Передать пакет для проверки')}</aside></div>`;
 const refresh=()=>$('#evidence-list').innerHTML=selected.map(i=>`<span>${escape(items[i][0])}</span>`).join('')||'<p>Пока пусто</p>';refresh();$$('[data-evidence]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.evidence),at=selected.indexOf(i);at>=0?selected.splice(at,1):selected.push(i);b.classList.toggle('selected',selected.includes(i));b.querySelector('small').textContent=selected.includes(i)?'В пакете':'Сохранить';G.action('evidence'+i);refresh();});$('#check-task').onclick=()=>{if(items.every((x,i)=>selected.includes(i)===x[1])){state.uses['Сделай скриншот']=(state.uses['Сделай скриншот']||0)+1;G.done('Ты сохранил существенные факты для помощи и не распространил личную ситуацию всем.');}else G.error('Проверь пакет: нужны содержание, источник и время. Публичная пересылка или чужие адреса не помогают безопасному обращению.');};
};
types.sources=(a,s)=>{
 const seen=G.data.seen||(G.data.seen=[]),selected=G.data.selected||(G.data.selected=[]);
 const available=s.sources.map((x,i)=>({source:x,index:i})).filter(x=>D.rank()!==0||x.index!==1);
 a.innerHTML=instruction('Открывай источники и читай сведения. Добавь независимые подтверждения в доску проверки.')+`<div class="source-lab"><div class="source-shelf">${available.map(({source:x,index:i})=>`<button class="source-file ${seen.includes(i)?'read':''}" data-source="${i}">${icon('search')}<b>${escape(x.name)}</b><span>${seen.includes(i)?'Исследован':'Открыть'}</span></button>`).join('')}</div><div class="source-desk" id="source-desk"><h3>Лабораторный стол</h3><p>Открой документ на полке слева.</p></div></div><div class="evidence-pins" id="source-pins"></div>${checkButton('Сопоставить подтверждения')}`;
 const pins=()=>$('#source-pins').innerHTML=selected.map(i=>`<button data-unpin="${i}">${escape(s.sources[i].name)} ×</button>`).join('')||'<span>Подтверждения пока не добавлены</span>';pins();
 $$('[data-source]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.source),source=s.sources[i];if(!seen.includes(i))seen.push(i);G.action('source'+i);b.classList.add('read');b.querySelector('span').textContent='Исследован';$('#source-desk').innerHTML=`<span class="eyebrow">ДОКУМЕНТ ${i+1}</span><h3>${escape(source.name)}</h3><p>${escape(source.text)}</p><button class="secondary" id="read-source">${icon('sound')} Прослушать документ</button><button class="secondary" id="pin-source">${selected.includes(i)?'Убрать с доски':'Добавить как подтверждение'}</button>`;$('#read-source').onclick=()=>D.voiceText(source.text,{manual:true});if(D.young())D.voiceText(source.text);$('#pin-source').onclick=()=>{const at=selected.indexOf(i);at>=0?selected.splice(at,1):selected.push(i);G.store();pins();$('#pin-source').textContent=selected.includes(i)?'Убрать с доски':'Добавить как подтверждение';};});
 $('#source-pins').onclick=e=>{const b=e.target.closest('[data-unpin]');if(b){selected.splice(selected.indexOf(Number(b.dataset.unpin)),1);G.store();pins();}};$('#check-task').onclick=()=>{if(available.every(({source:x,index:i})=>selected.includes(i)===x.ok))G.done('Подтверждения получены из независимых источников. Репост того же сообщения не добавляет нового факта.');else G.error('Сравни происхождение сведений. Нужны источники, которые получили информацию самостоятельно и указывают авторство, дату и контекст.');};
};
types.network=(a,s)=>{
 const items=sample(s.items),stopped=G.data.stopped||(G.data.stopped=[]),total=items.filter(x=>x[1]).length;
 a.innerHTML=instruction('Останавливай распространение в узлах сети. Нажми на действие, которое нужно прекратить.')+`<div class="network-board"><svg viewBox="0 0 700 360" preserveAspectRatio="none" aria-hidden="true">${items.map((x,i)=>`<path d="M350 180 L${70+(i%3)*280} ${70+Math.floor(i/3)*230}"/>`).join('')}</svg><div class="network-center">${icon('chat')}<b>Публикация</b></div>${items.map(([text],i)=>`<button class="network-node ${stopped.includes(i)?'stopped':''}" data-node="${i}" style="--x:${6+(i%3)*33}%;--y:${8+Math.floor(i/3)*65}%" ${stopped.includes(i)?'disabled':''}>${escape(text)}</button>`).join('')}</div><p id="network-count" class="task-counter">Остановлено ${stopped.length}/${total} цепочек</p>`;
 $$('[data-node]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.node);if(items[i][1]){stopped.push(i);b.disabled=true;b.classList.add('stopped');G.action('network'+i);$('#network-count').textContent=`Остановлено ${stopped.length}/${total} цепочек`;if(stopped.length===total)G.done('Ты остановил распространение унижения и сохранил действия поддержки.');}else G.error('Этот узел помогает получить поддержку и не распространяет унижение. Посмотри, где увеличивается аудитория обидного материала.');});
};
function offerGame(a,s){
 const seen=G.data.seen||(G.data.seen=[]);let selected=G.data.selected??null;const placed=G.data.placed??false;
 a.innerHTML=instruction(s.type==='trade'?'Исследуй обе сделки. Затем перенеси свой предмет в выбранный канал обмена.':'Открой сведения о продавцах. Затем перенеси товар в корзину выбранного магазина.')+`<div class="offer-items"><button data-drag="item" class="drag-card product-item">${icon(s.type==='trade'?'gamepad':'sound')}<span>${s.type==='trade'?'Мой игровой предмет':'Наушники · мой выбор'}</span></button></div><div class="offers">${s.offers.map((x,i)=>`<section class="offer-card ${selected===i?'selected':''}"><h3>${escape(x.name)}</h3><button class="secondary inspect-offer" data-offer="${i}">Исследовать условия</button><div class="offer-facts" id="offer-facts-${i}">${seen.includes(i)?x.facts.map(t=>`<p>${escape(t)}</p>`).join(''):''}</div><div data-drop="${i}" class="offer-drop" role="button" tabindex="0">${selected===i&&placed?'Предмет выбран для этого канала':'Перенеси предмет сюда'}</div></section>`).join('')}</div>${checkButton(s.type==='trade'?'Подтвердить обмен':'Перейти к оформлению')}`;
 $$('[data-offer]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.offer),description=s.offers[i].facts.join('. ');if(!seen.includes(i))seen.push(i);$('#offer-facts-'+i).innerHTML=s.offers[i].facts.map(t=>`<p>${escape(t)}</p>`).join('')+`<button class="secondary" data-read-offer="${i}">${icon('sound')} Прослушать условия</button>`;a.querySelector(`[data-read-offer="${i}"]`).onclick=()=>D.voiceText(description,{manual:true});G.action('offer'+i);if(D.young())D.voiceText(description);});
 drag(a,(id,slot)=>{selected=Number(slot);G.data.selected=selected;G.data.placed=true;$$('.offer-card').forEach((el,i)=>el.classList.toggle('selected',i===selected));$$('.offer-drop').forEach((el,i)=>el.textContent=i===selected?'Предмет выбран для этого канала':'Перенеси предмет сюда');G.action('offer-place'+slot);});
 $('#check-task').onclick=()=>{if(selected===null){G.error('Сначала исследуй условия и перенеси предмет в выбранный канал.');return;}if(seen.length<2){G.error('Для сравнения пока не хватает сведений. Исследуй условия обеих сторон.');return;}if(s.offers[selected].safe)G.done(s.type==='trade'?'Предмет передан через систему обмена. Пароль остался у тебя, а история сделки сохранена.':'Ты сравнил продавцов и условия. Выбран защищённый канал оплаты с понятными условиями возврата.');else G.error(s.type==='trade'?'Этот канал просит доступ к аккаунту и не сохраняет гарантии сделки. Предмет можно получить без передачи пароля.':'Перевод частному лицу и отсутствие сведений о продавце повышают риск. Скидка не заменяет проверку условий.');};
}
types.trade=offerGame;types.shop=offerGame;
types.cart=(a,s)=>{
 const rows=D.rank()===0?s.rows.slice(0,3):s.rows;
 const chosen=G.data.chosen||(G.data.chosen=rows.map(()=>true));
 a.innerHTML=instruction('Изменяй состав корзины. Общая стоимость обновляется после каждого действия.')+`<div class="cart-game"><div class="cart-rows">${rows.map(([text,price],i)=>`<label class="cart-row"><span><b>${escape(text)}</b><small>${price?price.toLocaleString('ru-RU')+' ₽':'Без разового платежа'}</small></span><input type="checkbox" data-cart="${i}" ${chosen[i]?'checked':''}><i class="switch"></i></label>`).join('')}</div><aside class="cart-total"><small>Итого к оплате</small><b id="cart-sum"></b><p id="cart-repeat"></p>${checkButton(s.close?'Закрыть без регистрации':'Подготовить заказ')}</aside></div>`;
 const refresh=()=>{$('#cart-sum').textContent=rows.reduce((sum,x,i)=>sum+(chosen[i]?x[1]:0),0).toLocaleString('ru-RU')+' ₽';$('#cart-repeat').textContent=rows.some((x,i)=>chosen[i]&&/ежемесячно|продлением/.test(x[0]))?'В корзине есть повторный платёж.':'Повторных платежей нет.';};refresh();$$('[data-cart]').forEach(el=>el.onchange=()=>{chosen[Number(el.dataset.cart)]=el.checked;G.action('cart'+el.dataset.cart);refresh();});$('#check-task').onclick=()=>{if(rows.every((x,i)=>x[2]===chosen[i]))G.done(s.close?'Ты закрыл предложение, не передав данные и не согласившись на скрытые платежи.':'Состав заказа соответствует выбору. Дополнительные услуги и подписка не включены без твоего решения.');else G.error('Сопоставь корзину с первоначальным выбором. Нулевой разовый платёж может сопровождаться передачей данных или будущим списанием.');};
};
/* Аркада использует время кадра; скорость одинакова на мониторах 60/144 Гц. */
types.runner=(a,s)=>{
 const target=D.rank()===0?5:D.rank()===1?6:8;let score=G.data.score||0,objects=[],x=350,last=0,spawn=0,running=false,raf=0,left=false,right=false,collisionLock=0;const good=s.good,bad=s.bad;
 a.innerHTML=instruction('Двигай героя мышью по полю, стрелками или кнопками. Спокойный ход позволяет рассмотреть и прослушать каждый предмет без таймера.')+`<div class="arcade-toolbar"><span id="runner-score">Собрано ${score}/${target}</span><button class="secondary" id="arcade-toggle">Начать</button><button class="secondary" id="arcade-step">Спокойный ход</button></div><div id="arcade-object" class="arcade-object" aria-live="polite"></div><canvas id="runner" width="700" height="370" aria-label="Аркадное поле. Управление стрелками или кнопками."></canvas><div class="arcade-controls"><button class="secondary" id="move-left" aria-label="Двигаться влево">←</button><span>Цель: ${target} безопасных действий · без штрафа за время</span><button class="secondary" id="move-right" aria-label="Двигаться вправо">→</button></div>`;
 const c=$('#runner'),ctx=c.getContext('2d'),heroImage=new Image();heroImage.src=D.hero().img;
 function add(){const isGood=Math.random()<.58;objects.push({x:90+Math.random()*520,y:-35,text:(isGood?good:bad)[Math.floor(Math.random()*(isGood?good:bad).length)],good:isGood});}
 function render(){ctx.clearRect(0,0,700,370);const bg=ctx.createLinearGradient(0,0,700,370);bg.addColorStop(0,'#121e42');bg.addColorStop(1,'#222044');ctx.fillStyle=bg;ctx.fillRect(0,0,700,370);ctx.strokeStyle='#344565';for(let j=0;j<9;j++){ctx.beginPath();ctx.moveTo(j*100-50,0);ctx.lineTo(350+(j-4)*200,370);ctx.stroke();}for(let y=30;y<370;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(700,y);ctx.stroke();}for(const o of objects){ctx.fillStyle='#243656';ctx.strokeStyle='#7e9cc4';ctx.lineWidth=1.5;ctx.beginPath();ctx.roundRect(o.x-83,o.y-17,166,35,9);ctx.fill();ctx.stroke();ctx.fillStyle='#f7fbff';ctx.font='14px Segoe UI';ctx.textAlign='center';ctx.fillText(o.text,o.x,o.y+5);}ctx.fillStyle=collisionLock>0?'#da7e8f':'#6bdacf';ctx.beginPath();ctx.ellipse(x,340,38,10,0,0,Math.PI*2);ctx.fill();if(heroImage.complete&&heroImage.naturalWidth)ctx.drawImage(heroImage,x-23,278,46,68);else{ctx.fillStyle='#75d4ff';ctx.beginPath();ctx.arc(x,315,18,0,7);ctx.fill();}ctx.fillStyle='#c9d9ee';ctx.font='12px Segoe UI';ctx.textAlign='left';ctx.fillText('Подписи важнее оформления',12,355);}
 function update(dt){collisionLock=Math.max(0,collisionLock-dt);if(left)x-=dt*270;if(right)x+=dt*270;x=Math.max(50,Math.min(650,x));spawn+=dt;if(spawn>1.9){add();spawn=0;}const speed=(state.settings.slow||D.young()?42:63+D.rank()*9);for(const o of objects){o.y+=dt*speed;if(!o.hit&&Math.abs(o.y-315)<24&&Math.abs(o.x-x)<57){o.hit=true;if(o.good){score++;G.data.score=score;G.action('runner'+score);D.effect('success');$('#runner-score').textContent=`Собрано ${score}/${target}`;if(score>=target){running=false;G.done('Ты собрал способы защиты, двигался самостоятельно и обходил рискованные действия.');return;}}else{collisionLock=.7;G.error(`«${o.text}» увеличивает риск. Ты сохраняешь собранные предметы и можешь продолжить.`);}}}objects=objects.filter(o=>o.y<410&&!o.hit);}
 function frame(now){const dt=Math.min(.05,(now-(last||now))/1000);last=now;if(running&&!G.paused&&!G.completed)update(dt);render();if(!G.completed)raf=requestAnimationFrame(frame);}
 function drawCalm(){const o=G.data.calmObject,p=$('#arcade-object');if(!o){p.innerHTML='';return;}p.innerHTML=`<div class="calm-choice"><b>${escape(o.text)}</b><button class="secondary" id="arcade-read">${icon('sound')} Прослушать предмет</button><div><button class="primary" id="arcade-collect">Собрать</button><button class="secondary" id="arcade-pass">Пропустить</button></div></div>`;$('#arcade-read').onclick=()=>D.voiceText(o.text,{manual:true});for(const [id,collect] of [['arcade-collect',true],['arcade-pass',false]])$('#'+id).onclick=()=>{if(G.paused||G.completed)return;const selected=G.data.calmObject;if(!selected)return;delete G.data.calmObject;G.data.calmTurns=(G.data.calmTurns||0)+1;if(selected.good===collect){if(collect){score++;G.data.score=score;G.action('runner'+score);$('#runner-score').textContent=`Собрано ${score}/${target}`;if(score>=target){drawCalm();G.done('Ты собрал способы защиты, действуя без спешки и пропуская рискованные предложения.');return;}}else G.action('runner-pass'+G.data.calmTurns,'Рискованное предложение пропущено. Данные и доступ остались у тебя.');}else G.error(collect?`«${selected.text}» увеличивает риск. Попробуй другой предмет.`:`«${selected.text}» помогает сохранить контроль. Попробуй собрать его в следующем ходе.`);drawCalm();G.store();};}
 $('#arcade-toggle').onclick=()=>{delete G.data.calmObject;drawCalm();running=!running;$('#arcade-toggle').textContent=running?'Пауза аркады':'Продолжить';};$('#arcade-step').onclick=()=>{if(G.paused||G.completed)return;running=false;$('#arcade-toggle').textContent='Продолжить';objects=[];if(!G.data.calmObject){add();const o=objects.pop();G.data.calmObject={text:o.text,good:o.good};G.store();}drawCalm();D.voiceText(G.data.calmObject.text);render();};drawCalm();
 const pointer=e=>{if(G.paused||G.completed)return;const rect=c.getBoundingClientRect();x=(e.clientX-rect.left)/rect.width*700;x=Math.max(50,Math.min(650,x));};c.onpointermove=pointer;c.onpointerdown=pointer;
 const keydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();e.key==='ArrowLeft'?left=true:right=true;}if(e.code==='Space'&&e.target===document.body){e.preventDefault();$('#arcade-toggle').click();}};
 const keyup=e=>{if(e.key==='ArrowLeft')left=false;if(e.key==='ArrowRight')right=false;};document.addEventListener('keydown',keydown);document.addEventListener('keyup',keyup);
 for(const [id,dir] of [['move-left',-1],['move-right',1]]){const b=$('#'+id);b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);dir<0?left=true:right=true;};b.onpointerup=b.onpointercancel=()=>{left=right=false;};b.onclick=()=>{x=Math.max(50,Math.min(650,x+dir*70));render();};}
 raf=requestAnimationFrame(frame);G.cleanup.push(()=>{cancelAnimationFrame(raf);document.removeEventListener('keydown',keydown);document.removeEventListener('keyup',keyup);});
};
types.shield=(a,s)=>{
 const total=D.young()?5:8;let n=G.data.n||0,round=G.data.round||0,paused=false,timer=0,remaining=7;
 a.innerHTML=instruction('Закрывай появляющиеся уязвимости. Полезные настройки оставляй работать.')+`<div class="vault-meter"><span id="shield-count">Закрыто ${n}/${total}</span><button class="secondary" id="shield-pause">Пауза сейфа</button></div><div class="vault-arena"><div class="vault-core">${icon('shield')}<span>Цифровой сейф</span></div><div class="vault-events" id="vault-events"></div></div>`;
 function draw(){const rows=shuffled([...s.bad.map(t=>[t,true]),...s.good.map(t=>[t,false])]).slice(0,D.rank()===0?3:4);if(!rows.some(x=>x[1]))rows[0]=[s.bad[round%s.bad.length],true];$('#vault-events').innerHTML=rows.map(([t,b],i)=>`<button class="vault-event" data-vault="${i}">${escape(t)}</button>`).join('');$$('[data-vault]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.vault);if(rows[i][1]){n++;G.data.n=n;G.action('leak'+n,'Источник утечки закрыт. Полезные функции остаются включёнными.');$('#shield-count').textContent=`Закрыто ${n}/${total}`;if(n>=total){G.done('Сейф защищён: ты закрыл уязвимости, сохранив полезные функции.');return;}round++;G.data.round=round;G.store();draw();remaining=7;}else G.error('Этот параметр поддерживает защиту. Ищи настройку, которая раскрывает личные данные или даёт чужой доступ.');});}
 draw();$('#shield-pause').onclick=()=>{paused=!paused;$('#shield-pause').textContent=paused?'Продолжить сейф':'Пауза сейфа';};timer=setInterval(()=>{if(!paused&&!G.paused&&!G.completed&&!D.young()&&!state.settings.slow){remaining--;if(remaining<=0){round++;draw();remaining=7;}}},1000);G.cleanup.push(()=>clearInterval(timer));
};
types.maze=(a,s)=>{
 let position=G.data.position||(G.data.position=[...s.start]);const visited=G.data.visited||(G.data.visited=[]);const eq=(p,q)=>p[0]===q[0]&&p[1]===q[1];
 function draw(){a.innerHTML=instruction('Нажимай соседнюю клетку, используй стрелки или кнопки направления. Сначала посети две точки проверки.')+`<div class="maze-layout"><div class="maze-board" role="group" aria-label="Лабиринт">${Array.from({length:30},(_,i)=>{const p=[i%6,Math.floor(i/6)],wall=s.walls.some(x=>eq(x,p)),risk=s.risks.some(x=>eq(x,p)),cp=s.checkpoints.findIndex(x=>eq(x,p)),goal=eq(s.goal,p),player=eq(position,p);return `<button class="maze-cell ${wall?'wall':''} ${risk?'risk-cell':''} ${player?'player':''} ${visited.includes(cp)?'visited':''}" data-cell="${p.join(',')}" ${wall?'disabled':''} aria-label="Клетка ${p[0]+1},${p[1]+1}${player?', герой':''}">${player?`<img src="${D.hero().img}" alt="Герой">`:goal?icon('life'):cp>=0?icon(cp===0?'camera':'search'):risk?'Личные данные':''}</button>`;}).join('')}</div><aside><h3>Маяк помощи</h3><p>Точки проверки: ${visited.length}/2</p><p>У стен прохода нет. Рискованную клетку можно обойти.</p><div class="maze-controls"><button data-dir="0,-1">↑</button><button data-dir="-1,0">←</button><button data-dir="1,0">→</button><button data-dir="0,1">↓</button></div></aside></div>`;}
 function move(p){if(G.completed||G.paused||p[0]<0||p[0]>5||p[1]<0||p[1]>4||s.walls.some(x=>eq(x,p)))return;if(Math.abs(p[0]-position[0])+Math.abs(p[1]-position[1])!==1){D.toast('Можно перейти только в соседнюю клетку.');return;}if(s.risks.some(x=>eq(x,p))){G.error('Этот путь предлагает передать личные данные до проверки. Поищи другой проход.');return;}position=p;G.data.position=position;const cp=s.checkpoints.findIndex(x=>eq(x,p));if(cp>=0&&!visited.includes(cp)){visited.push(cp);G.action('checkpoint'+cp);}else G.store();draw();if(eq(position,s.goal)){if(visited.length===2)G.done('Ты добрался к поддержке, сохранив сведения и проверив ситуацию до решения.');else G.feedback(false,'До маяка нужно посетить обе точки проверки. Можно вернуться и собрать сведения.');}}
 draw();a.addEventListener('click',e=>{const b=e.target.closest('[data-cell]'),d=e.target.closest('[data-dir]');if(b)move(b.dataset.cell.split(',').map(Number));else if(d){const v=d.dataset.dir.split(',').map(Number);move([position[0]+v[0],position[1]+v[1]]);}});const keys=e=>{const dirs={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};if(dirs[e.key]){e.preventDefault();move([position[0]+dirs[e.key][0],position[1]+dirs[e.key][1]]);}};document.addEventListener('keydown',keys);G.cleanup.push(()=>document.removeEventListener('keydown',keys));
};
const caseTools={data:['Стоп','Проверь источник','Проверь источник','Не сообщай код'],social:['Стоп','Проверь источник','Настрой приватность','Попроси помощи'],links:['Стоп','Проверь источник','Проверь источник','Стоп'],pressure:['Стоп','Сделай скриншот','Заблокируй','Попроси помощи'],conflict:['Стоп','Сделай скриншот','Заблокируй','Попроси помощи'],truth:['Стоп','Проверь источник','Проверь источник','Проверь источник'],games:['Не сообщай код','Проверь источник','Стоп','Стоп'],money:['Стоп','Проверь источник','Проверь источник','Стоп'],free:['Стоп','Проверь источник','Не сообщай код','Попроси помощи'],help:['Стоп','Сделай скриншот','Проверь источник','Попроси помощи']};
const casePrompts={
 data:['Сообщение ждёт твоих данных. Как начнёшь?','Каким способом получишь сведения о сервисе?','Что поможет сопоставить запрос с настоящими уведомлениями?','Как поступишь с данными, которые дают доступ к аккаунту?'],
 social:['Новый контакт ждёт ответа на личную просьбу. Как начнёшь?','Пока есть только слова собеседника. Где взять подтверждение?','Что делать с видимостью личных сведений и запросами контакта?','Что поможет, если безопасность встречи или общения не ясна?'],
 links:['Письмо предлагает переход или загрузку. Твоё первое действие?','Каким каналом узнаешь, действительно ли сервис отправил запрос?','Как сопоставишь просьбу с независимо полученными сведениями?','Что делать с файлом или формой из неподтверждённого сообщения?'],
 pressure:['Требование сопровождается угрозой. Как начнёшь?','Какие сведения пригодятся, если понадобится помощь?','Каким инструментом можно изменить доступ собеседника к тебе?','Что поможет, если угрозы продолжаются?'],
 conflict:['Публикация ждёт твоей реакции. Как поступишь первым делом?','Что позволит показать факты человеку, который поможет?','Каким инструментом сервиса можно ограничить нежелательный контакт?','Какая поддержка нужна, если вред продолжается?'],
 truth:['Публикацию предлагают переслать. Твоё первое действие?','Пока неизвестно происхождение сведений. Что поможет?','Что позволит установить дату и полный контекст?','Что поможет отличить подтверждение от копии одного сообщения?'],
 games:['Предложение затрагивает доступ к аккаунту. Как его сохранить?','Где проверить условия и правила предложения?','Защиту устройства предлагают изменить. Как поступишь до проверки?','Риск по-прежнему остаётся. Как завершить сомнительную операцию?'],
 money:['От тебя ждут денег или доступа к счёту. Как начнёшь?','Просьба пришла через сообщение. Как получить независимое подтверждение?','Что поможет разобраться в получателе, организации и условиях?','Операция остаётся непонятной. Как поступишь с переводом?'],
 free:['Предложение приглашает участвовать. Твоё первое действие?','Что поможет увидеть реальные условия за рекламной фразой?','Форма просит чувствительные сведения. Как сохранить контроль?','Что поможет, если после проверки всё ещё есть сомнение?'],
 help:['Ситуация непонятна, но ждёт твоего действия. Как начнёшь?','Как зафиксировать доступные факты для совместного разбора?','Что поможет уменьшить неопределённость?','Существенный риск остался. Какой ресурс можно привлечь?']
};
function caseConfiguration(id,age=state.age){
 const r=Object.keys(D.ageNames).indexOf(age);
 let tools=[...caseTools[id]],prompts=[...casePrompts[id]],plan=[...DN_CONTENT.plans[id]];
 if(r===0){tools=[id==='games'?'Не сообщай код':'Стоп','Попроси помощи'];prompts=['На экране просьба или предложение. Как начнёшь?','Ты не уверен, что делать дальше. Кто может помочь?'];}
 else if(r===1){tools=id==='data'||id==='pressure'?['Не сообщай код','Стоп','Попроси помощи']:['Стоп','Проверь источник','Попроси помощи'];prompts=['От тебя ждут действия или личных сведений. Как сохранить контроль?','Что поможет приостановить или проверить просьбу?','Если просьба всё ещё вызывает сомнение, какой ресурс доступен?'];}
 else if(id==='games'&&r===4){tools=['Стоп','Проверь источник','Стоп','Попроси помощи'];prompts=['Программа требует установки и изменения защиты. Твоё первое действие?','Где можно проверить происхождение программы и правила игры?','Как поступить с защитой, пока источник не подтверждён?','Если самостоятельно оценить риск не получилось, какой ресурс доступен?'];}
 else if(id==='data'&&r===3){tools=['Стоп','Проверь источник','Проверь источник','Настрой приватность'];prompts=['Форма просит личные сведения. Как начнёшь?','Что поможет установить организатора и назначение сбора?','Как сопоставить адрес ресурса с известным организатором?','Что делать с избыточными личными сведениями до подтверждения?'];}
 if(r<2||id==='games'&&r===4||id==='data'&&r===3){const labels={'Стоп':'Приостановить действие до проверки','Проверь источник':'Проверить через надёжный независимый канал','Не сообщай код':'Сохранить пароль и код у себя','Настрой приватность':'Сохранить контроль личных сведений','Попроси помощи':'Показать ситуацию подходящему взрослому'};plan=tools.map(t=>labels[t]);}
 return {tools,prompts,plan};
}
function toolConsequence(name){return({'Стоп':'Действие приостановлено. Данные, деньги и файлы пока не переданы. Есть время для проверки.','Проверь источник':'Выбран независимый канал проверки. Сопоставь известный адрес, автора и условия; слова отправителя сами по себе не являются подтверждением.','Не сообщай код':'Пароль и код не переданы. Контроль доступа остался у тебя.','Сделай скриншот':'Сохранены содержание, отправитель и время — для проверки с тем, кто поможет.','Заблокируй':'Нежелательный контакт ограничен средствами учебного сервиса. Можно дополнительно использовать жалобу.','Настрой приватность':'Личные сведения не публикуются автоматически и не передаются непроверенному контакту.','Попроси помощи':'Ситуация показана подходящему доверенному человеку. Для младших это следующий шаг при сомнении; для старших — ресурс при неопределённости.'})[name];}
types.case=(a,s)=>{
 const c=window.IAR_CASES[G.w.number-1].ages[state.age],progress=G.data.progress||0;let at=progress;const {plan,prompts,tools}=caseConfiguration(G.w.id);let reflection=G.data.reflection||'';
 function draw(){const complete=at>=plan.length;
 a.innerHTML=instruction('Выбери инструмент рюкзака и перенеси его к ситуации. При необходимости нажми карточку, затем на область действия.')+`<div class="case-simulator"><div class="case-phone"><div class="messenger-top">${icon(G.w.icon)}<b>Твоя ситуация</b><span>${Math.min(at+1,tools.length)}/${tools.length}</span></div><div class="case-messages"><div class="bubble npc">${escape(c.situation)}</div>${plan.slice(0,at).map((p,i)=>`<div class="bubble self">${escape(p)}</div><div class="bubble system">${escape(toolConsequence(tools[i]))}</div>`).join('')}</div>${!complete?`<div class="case-target" data-drop="action" tabindex="0" role="button"><small>ЗАДАЧА СЕЙЧАС</small><b>${escape(prompts[at])}</b><span>Примени подходящий инструмент</span></div>`:''}</div><aside class="case-tools"><h3>${icon('bag')} Твой рюкзак</h3><div class="case-tool-bank">${state.inventory.map(name=>`<button class="drag-card tool-card" data-drag="${escape(name)}">${icon(DN_CONTENT.tools[name]?.icon)}${escape(name)}</button>`).join('')}</div>${!complete?'<button class="secondary unsafe-case" id="unsafe-case">Выполнить исходную просьбу сразу</button>':''}<span class="case-use-note">Применено действий: ${at} / ${tools.length}</span></aside></div>${complete?`<div class="reflection-panel"><h3>Что изменилось после твоих действий?</h3><p>${escape(c.safe)}</p>${D.rank()>=2?`<label>Объясни своё решение для обсуждения с педагогом<textarea id="reflection" maxlength="600" rows="3" placeholder="Какие признаки и последствия ты учёл?">${escape(reflection)}</textarea></label><p class="small-note">Объяснение сохраняется для обсуждения. Тренажёр не оценивает свободный текст автоматически.</p>`:''}${checkButton('Завершить ситуацию')}</div>`:''}`;
 if(!complete){$('#unsafe-case').onclick=()=>{G.error(unsafeConsequence(G.w.id)+' Можно остановиться и изменить действие.');$('.case-messages').insertAdjacentHTML('beforeend',`<div class="bubble system warning">${escape(unsafeConsequence(G.w.id))}</div>`);};}
 else{if($('#reflection'))$('#reflection').oninput=e=>{reflection=e.target.value;G.data.reflection=reflection;G.store();};$('#check-task').onclick=()=>{if(D.rank()>=2&&reflection.trim().length<8){D.toast('Добавь короткое объяснение: какой признак ты заметил и почему это действие снижает риск.');$('#reflection').focus();return;}state.results[G.k]=state.results[G.k]||undefined;G.done((D.young()?'Ты остановился и привлёк поддержку в новой ситуации. ':'Ты перенёс способ действия в новую ситуацию: остановился, проверил и выбрал безопасное действие. ')+c.safe);if(state.results[G.k]){state.results[G.k].reflection=reflection;D.save();}};}
 }
 draw();drag(a,(name,zone)=>{if(zone!=='action'||at>=tools.length)return;if(name===tools[at]){state.uses[name]=(state.uses[name]||0)+1;G.action('case'+at,toolConsequence(name));at++;G.data.progress=at;G.store();draw();}else G.error(`Инструмент «${name}» полезен в другой задаче. Сейчас подумай: ${prompts[at]}`);});
};
function unsafeConsequence(id){return({data:'Передача кода или пароля может дать другому человеку доступ к аккаунту.',social:'Личные сведения и секретная встреча увеличивают риск, пока собеседник не проверен.',links:'Ссылка и вложение могут вести к краже доступа. Имя адресата не подтверждает письмо.',pressure:'Выполнение требования не гарантирует прекращение давления.',conflict:'Пересылка или ответная травля увеличивают вред и аудиторию унижения.',truth:'Пересылка до проверки распространяет сведения, подлинность которых неизвестна.',games:'Передача аккаунта или отключение защиты может лишить доступа и повредить устройству.',money:'Чужая просьба о переводе может привести к потере денег или вовлечению в непонятную схему.',free:'После бонуса могут потребовать личные данные, деньги и повторные платежи.',help:'Поспешное действие при неопределённости может увеличить риск.'})[id];}
function caseConsequence(id,i){const phrases={
 data:['Ввод приостановлен. Данные ещё не переданы.','Известное приложение открыто независимо от сообщения.','Запрос сверяется с уведомлениями и настройками аккаунта.','Пароль и код не переданы человеку. Контроль аккаунта сохранён.'],
 social:['Личные требования не выполняются автоматически.','Сведения сопоставляются с независимым источником; фотография не считается доказательством.','Личные сведения остаются под твоим контролем.','Контакт обсуждается с доверенным человеком. При риске можно прекратить общение.'],
 links:['Переход и загрузка приостановлены.','Сервис открыт по известному адресу.','Просьба проверяется другим каналом; данные из письма сами по себе ничего не доказывают.','Неизвестное вложение не запущено.'],
 pressure:['Неприятное требование не выполнено.','Важные сообщения, отправитель и время сохранены.','Нежелательный контакт ограничен средствами сервиса.','Ты получил ресурс поддержки, не вступая в ответную угрозу.'],
 conflict:['Ты не добавляешь аудиторию травле.','Факты сохранены для обращения, без публичной пересылки.','Жалоба и ограничения применяются по ситуации.','Педагог или доверенный взрослый может подключиться к снижению вреда.'],
 truth:['Непроверенная публикация не распространяется.','Найдено происхождение сведений; отсутствие автора отмечено как неопределённость.','Дата, полная версия и подпись сравниваются.','Копии одного сообщения отделены от независимых сведений. Вывод делается после проверки.'],
 games:['Доступ к аккаунту остался у тебя.','Предложение сопоставлено с официальными правилами и каналом игры.','Защита устройства не отключена ради обещания преимущества.','Сомнительное действие отклонено.'],
 money:['Деньги ещё не отправлены.','Просьба сверяется с ранее известным каналом связи.','Условия, организация и получатель проверяются до любой операции.','Непонятная операция не выполняется; при сомнении можно обратиться за консультацией.'],
 free:['Участие и регистрация не начаты.','Обещания сопоставлены с реальными условиями, а не с рекламным слоганом.','Персональные и платёжные данные не переданы, деньги не отправлены.','Сомнительное предложение можно обсудить; для старших учитывается ограничение 18+.'],
 help:['Ты получил время для анализа, не действуя наугад.','Неизвестное и доступные факты зафиксированы.','Надёжные сведения отделены от предположений.','Если существенная неопределённость остаётся, поддержка помогает снизить риск.']
};return phrases[id][i];}
function final(a){
 let at=state.final[state.age]?.at||0;let mistakes=state.final[state.age]?.mistakes||0;const order=DN_CONTENT.worlds;
 function persist(){state.final[state.age]={...state.final[state.age],at,mistakes};D.save();}
 function draw(){if(at>=10){a.innerHTML=`<div class="route-finish">${icon('trophy')}<h2>Безопасный день завершён!</h2><p>Все десять тем встретились в одном маршруте. Ты применял проверку и поддержку в изменяющихся ситуациях.</p><div class="stats-strip"><span><b>${state.xp}</b> XP</span><span><b>${D.stars()}</b> звёзд</span><span><b>${mistakes}</b> исправлений</span></div><button class="primary" id="final-map">На карту</button><button class="secondary" id="final-repeat">Пройти день снова</button></div>`;$('#final-map').onclick=D.app.map;$('#final-repeat').onclick=()=>{at=0;mistakes=0;persist();draw();};return;}
 const w=order[at],c=IAR_CASES[w.number-1].ages[state.age];a.innerHTML=`<div class="day-progress"><div class="meter"><i style="width:${at*10}%"></i></div><span>Событие ${at+1}/10 · ${escape(w.title)}</span></div><div class="final-scene"><span class="eyebrow">${String(9+at).padStart(2,'0')}:15 · СОБЫТИЕ ДНЯ</span><h2>${escape(c.situation)}</h2><p>Выбери инструмент для первого действия. Затем прочитай его последствие и объясни, что проверишь дальше.</p><div class="final-tools">${shuffled(state.inventory).map(name=>`<button class="secondary" data-day-tool="${escape(name)}">${icon(DN_CONTENT.tools[name]?.icon)}${escape(name)}</button>`).join('')}</div><div id="day-feedback" role="status"></div></div>`;
 $$('[data-day-tool]').forEach(b=>b.onclick=()=>{const name=b.dataset.dayTool,expected=caseConfiguration(w.id).tools[0];if(name===expected||(name==='Попроси помощи'&&D.young())){state.uses[name]=(state.uses[name]||0)+1;persist();$('#day-feedback').innerHTML=`<div class="feedback good"><p>${escape(toolConsequence(name))}</p></div><label>Следующая проверка или действие<textarea id="day-reflection" rows="2" maxlength="400" placeholder="Что проверишь и к кому обратишься при сомнении?"></textarea></label><button class="primary" id="next-day">Продолжить день</button>`;$('#next-day').onclick=()=>{const text=$('#day-reflection').value.trim();if(!D.young()&&text.length<8){D.toast('Запиши следующее действие для обсуждения.');return;}const previous=state.final[state.age]?.reflections||[];previous[at]=text;at++;const won=at===10;if(won&&!state.final[state.age]?.rewarded){state.xp+=200;}const awarded=state.final[state.age]?.rewarded||won;state.final[state.age]={at,mistakes,reflections:previous,rewarded:awarded};D.save();D.app.refreshHeader();D.effect(won?'reward':'success');draw();};}else{mistakes++;persist();$('#day-feedback').innerHTML=`<div class="feedback bad"><p>Этот инструмент может пригодиться позже. Сначала нужно приостановить рискованное действие или сохранить контроль аккаунта. Попробуй изменить выбор.</p></div>`;D.effect('error');}});
 }
 draw();return ()=>{};
}
window.DN.games={mount,final,types,caseTools,caseConfiguration};
})();
